# Generated by Django 2.1.5 on 2021-06-06 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_out'),
    ]

    operations = [
        migrations.DeleteModel(
            name='out',
        ),
    ]
