# Generated by Django 2.1.5 on 2021-06-06 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_finder', '0002_auto_20210606_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='meta_data_container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyword_finder.info'),
        ),
    ]
